# Generated by Django 4.2.3 on 2023-07-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='server',
            field=models.CharField(default='', max_length=100),
        ),
    ]
